workflows:
  ios-release:
    name: iOS Build
    environment:
      flutter: stable          # 使用最新的稳定版 Flutter
      xcode: latest            # 使用最新的 Xcode 版本
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --export-method ad-hoc \
    artifacts:
      - build/ios/ipa/*.ipa